Fix mirror-server scripts to use proper log4j version
Otherwise it fails as follows:

$ ./mirror-server.sh
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
        at org.apache.jmeter.protocol.http.control.HttpMirrorServer.main(HttpMirrorServer.java:234)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

git-svn-id: https://svn.apache.org/repos/asf/jmeter/trunk@1844956 13f79535-47bb-0310-9956-ffa450edef68

Former-commit-id: 92323e8e54f8300f588a5cbd32aaad1f4f26158f