Hi,
Whe you add a CSV Data Set Config in your test plan and you don't fill
the filename field we have an exception

ERROR - jmeter.threads.JMeterThread: Test failed!
java.lang.IllegalArgumentException: Could not read file header line
	at
org.apache.jmeter.services.FileServer.reserveFile(FileServer.java:280)
	at
org.apache.jmeter.config.CSVDataSet.iterationStart(CSVDataSet.java:178)
	at
org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
	at
org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)
	at
org.apache.jmeter.control.GenericController.next(GenericController.java:158)
	at
org.apache.jmeter.control.LoopController.next(LoopController.java:123)
	at
org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:238)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\XXXXXXXXX (Accès refusé)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at
org.apache.jmeter.services.FileServer.createBufferedReader(FileServer.java:419)
	at org.apache.jmeter.services.FileServer.readLine(FileServer.java:345)
	at org.apache.jmeter.services.FileServer.readLine(FileServer.java:329)
	at
org.apache.jmeter.services.FileServer.reserveFile(FileServer.java:277)
	... 8 more

Antonio